server:
  port: 8083
  shutdown: graceful

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:35432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: 127.0.0.1
    port: 1025
    username: PLACEHOLDER
    password: PLACEHOLDER
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# Notification Service Configuration
notification:
  order-events-exchange: orders-exchange
  new-orders-queue: new-orders
  delivered-orders-queue: delivered-orders
  cancelled-orders-queue: cancelled-orders
  error-orders-queue: error-orders
  support-email: siva@sivalabs.com

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0

---
spring.config.activate.on-profile: docker

spring:
  datasource:
    url: jdbc:postgresql://notification-db:5432/postgres
  rabbitmq:
    host: rabbitmq
  mail:
    host: mailhog

management:
  tracing:
    enabled: true
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans