version: '3'

vars:
  GOOS: "{{default OS .GOOS}}"
  MVNW: '{{if eq .GOOS "windows"}}mvnw.cmd{{else}}./mvnw{{end}}'
  DC_DIR: "deployment/docker-compose"
  INFRA_DC_FILE: "{{.DC_DIR}}/infra.yml"
  APPS_DC_FILE: "{{.DC_DIR}}/apps.yml"
  MONITORING_DC_FILE: "{{.DC_DIR}}/monitoring.yml"
  SLEEP_CMD: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'
  USER: "chensoul"
  IMAGE_PREFIX: "bookstore"

tasks:
  default:
    cmds:
      - task: test
  test:
    deps: [format]
    cmds:
      - "{{.MVNW}} clean verify"

  format:
    cmds:
      - "{{.MVNW}} spotless:apply"

  build:
    cmds:
      - "{{.MVNW}} -pl catalog-service spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName={{.USER}}/{{.IMAGE_PREFIX}}-catalog-service"
      - "{{.MVNW}} -pl order-service spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName={{.USER}}/{{.IMAGE_PREFIX}}-order-service"
      - "{{.MVNW}} -pl notification-service spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName={{.USER}}/{{.IMAGE_PREFIX}}-notification-service"
      - "{{.MVNW}} -pl api-gateway spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName={{.USER}}/{{.IMAGE_PREFIX}}-api-gateway"
      - "{{.MVNW}} -pl webapp spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName={{.USER}}/{{.IMAGE_PREFIX}}-webapp"

  docker-build:
    cmds:
      - "{{.MVNW}} clean package"
      - "cd catalog-service && docker build -t  {{.USER}}/{{.IMAGE_PREFIX}}-catalog-service ."
      - "cd order-service && docker build -t  {{.USER}}/{{.IMAGE_PREFIX}}-order-service ."
      - "cd notification-service && docker build -t  {{.USER}}/{{.IMAGE_PREFIX}}-notification-service ."
      - "cd api-gateway && docker build -t  {{.USER}}/{{.IMAGE_PREFIX}}-api-gateway ."
      - "cd webapp && docker build -t  {{.USER}}/{{.IMAGE_PREFIX}}-webapp ."

  start_infra:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} up -d"

  stop_infra:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} stop"
      - "docker compose -f {{.INFRA_DC_FILE}} rm -f"

  restart_infra:
    cmds:
      - task: stop_infra
      - task: sleep
      - task: start_infra

  start_monitoring:
    cmds:
      - "docker compose -f {{.MONITORING_DC_FILE}} up -d"

  stop_monitoring:
    cmds:
      - "docker compose -f {{.MONITORING_DC_FILE}} stop"
      - "docker compose -f {{.MONITORING_DC_FILE}} rm -f"

  restart_monitoring:
    cmds:
      - task: stop_monitoring
      - task: sleep
      - task: start_monitoring

  start:
    deps: [build]
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} up -d"

  stop:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} stop"
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} rm -f"

  restart:
    cmds:
      - task: stop
      - task: sleep
      - task: start

  sleep:
    vars:
      DURATION: "{{default 5 .DURATION}}"
    cmds:
      - "{{.SLEEP_CMD}} {{.DURATION}}"
