server:
  port: 8989
  shutdown: graceful

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-methods: "*"
                allowed-headers: "*"
                allow-credentials: false
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST
          routes:
            - id: catalog-service
              uri: http://localhost:8081
              predicates:
                - Path=/catalog/**
              filters:
                - RewritePath=/catalog/?(?<segment>.*), /${segment}
            - id: orders-service
              uri: http://localhost:8082
              predicates:
                - Path=/orders/**
              filters:
                - RewritePath=/orders/?(?<segment>.*), /${segment}
            - id: openapi
              uri: http://localhost:${server.port}
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0

---
spring:
  config:
    import:
      - optional:nacos:application.yaml
      - optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        watch:
          enabled: true
          watch-delay: 1000
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yaml

---
spring.config.activate.on-profile: docker

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalog-service
              uri: http://catalog-service:8081
              predicates:
                - Path=/catalog/**
              filters:
                - RewritePath=/catalog/?(?<segment>.*), /${segment}
            - id: orders-service
              uri: http://order-service:8082
              predicates:
                - Path=/orders/**
              filters:
                - RewritePath=/orders/?(?<segment>.*), /${segment}
            - id: openapi
              uri: http://localhost:${server.port}
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs

management:
  tracing:
    enabled: true
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
