name: 'spring-boot-microservices-course'
services:
  catalog-service:
    image: chensoul/bookstore-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    ports:
      - "8081:8080"
    restart: unless-stopped
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  order-service:
    image: chensoul/bookstore-order-service
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    ports:
      - "8082:8080"
    restart: unless-stopped
    depends_on:
      order-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  notification-service:
    image: chensoul/bookstore-notification-service
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    ports:
      - "8083:8080"
    restart: unless-stopped
    depends_on:
      notification-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  api-gateway:
    image: chensoul/bookstore-api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    ports:
      - "8989:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  webapp:
    image: chensoul/bookstore-webapp
    container_name: webapp
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"