name: spring-boot-microservices-course

services:
  nacos:
    image: nacos/nacos-server:v3.0.3-slim
    container_name: nacos
    restart: always
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - NACOS_AUTH_IDENTITY_KEY=KEY_123456
      - NACOS_AUTH_IDENTITY_VALUE=VALUE_123456
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    ports:
      - "8848:8848"
      - "9848:9848"
      - "8838:8080"

  xxljob:
    image: xuxueli/xxl-job-admin:3.3.2
    container_name: xxljob
    ports:
      - "8868:8080"
    environment:
      PARAMS: '
          --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
          --spring.datasource.username=root
          --spring.datasource.password=123456
          --xxl.job.accessToken=xxl-job'

  spring-boot-admin:
    image: codecentric/spring-boot-admin:3.4.1
    ports:
      - "7010:7010"

  sentinel-dashboard:
    image: bladex/sentinel-dashboard:1.8.9
    container_name: sentinel-dashboard
    restart: always
    ports:
      - "8858:8858"

  seata-server:
    image: apache/seata-server:2.5.0
    hostname: seata-server
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 123456
    command: [
      'mysqld',
      '--log-bin=mysql-bin',
      '--binlog_format=ROW',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    volumes:
      - ./mysql/nacos.sql:/docker-entrypoint-initdb.d/nacos.sql:ro
      - ./mysql/bookstore.sql:/docker-entrypoint-initdb.d/bookstore.sql:ro
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - "3306:3306"

  redis:
    image: redis:8
    container_name: redis
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    command: "redis-server --appendonly yes"
    healthcheck:
      test: [ "CMD", "redis-cli","--raw", "incr","ping" ]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 500m

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    command: [ 'start-dev', '--import-realm', '--http-port=9191' ]
    container_name: keycloak
    hostname: keycloak
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin1234
    ports:
      - "9191:9191"
    deploy:
      resources:
        limits:
          memory: 2gb