server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3200

  distributor:
    receivers:
      zipkin:

  storage:
    trace:
      backend: local
      local:
        path: /tmp/tempo/blocks

  usage_report:
    reporting_enabled: false