name: API Gateway

on:
  push:
    paths:
      - api-gateway/**
    branches:
      - 'main'
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./api-gateway
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/bookstore-api-gateway
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -ntp verify

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Publish Docker Image
        run: |
          DOCKER_IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/bookstore-$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$DOCKER_IMAGE_NAME
          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
          docker push $DOCKER_IMAGE_NAME
